[workspace]
members = ["prestige", "cli", "macros"]

resolver = "3"

[workspace.package]
version = "0.3.2"
authors = ["Jeff Grunewald <jeff@grunewalddesign.com>"]
readme = "README.md"
description = "Library for creating streaming sources and sinks for efficient iceberg tables and parquet files in S3-compatible object storage"
homepage = "https://github.com/jeffgrunewald/prestige"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeffgrunewald/prestige"
keywords = ["s3", "parquet", "sink", "streaming", "iceberg"]
categories = ["asynchronous", "encoding", "filesystem"]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
async-trait = "0"
aws-config = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio", "credentials-process", "sso"] }
aws-sdk-s3 = { version = "1", default-features = false, features = ["sigv4a", "default-https-client", "rt-tokio"] }
aws-smithy-types-convert = { version = "0", features = ["convert-streams"] }
blake3 = "1"
bytes = "1"
chrono = { version = "0", features = ["serde"] }
config = { version = "0", default-features = false, features = ["toml"] }
derive_builder = "0.20"
futures = "0"
futures-util = "0"
iceberg = "0.8"
iceberg-catalog-rest = "0.8"
iceberg-catalog-sql = "0.8"
parquet = { version = "57", features = ["async"] }
regex = "1"
retainer = "0.3"
rust_decimal = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_arrow = { version = "0.14", features = ["arrow-57"] }
serde_json = "1"
sha2 = "0"
sqlx = { version = "0", features = ["postgres", "uuid", "chrono", "macros", "runtime-tokio-rustls"] }
super-visor = { version = "0" }
thiserror = "1"
tokio = { version = "1", default-features = false, features = [
  "fs",
  "macros",
  "rt-multi-thread",
] }
tokio-stream = "0"
tracing = "0"
tempfile = "3"
