[package]
name = "prestige-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI interface for manually fetching and reading Prestige-parquet files"

[[bin]]
name = "prestige"
path = "src/main.rs"

[dependencies]
prestige = { version = "0.2.2", path = "../prestige" }
clap = { version = "4", features = ["derive"] }
