[package]
name = "prestige"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Prestige file reading and writing utilities and tools"

[dependencies]
anyhow.workspace = true
arrow = { version = "55", features = ["ipc"] }
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-types-convert.workspace = true
blake3.workspace = true
bytes.workspace = true
chrono.workspace = true
config.workspace = true
derive_builder.workspace = true
futures.workspace = true
futures-util.workspace = true
metrics = { version = "0.24", optional = true }
opentelemetry = { version = "0.31", optional = true, default-features = false, features = ["metrics"] }
parquet = { version = "55", features = ["async"] }
prestige-macros = { version = "0.2.4", path = "../macros" }
regex.workspace = true
retainer.workspace = true
rust_decimal = { workspace = true, optional = true }
serde.workspace = true
serde_arrow.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx = { workspace = true, optional = true }
super-visor.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_bytes = "0"
tempfile.workspace = true
tokio-util = "0"

[features]
default = []
decimal = ["dep:rust_decimal"]
metrics = ["dep:metrics"]
opentelemetry = ["dep:opentelemetry"]
sqlx-postgres = ["sqlx/postgres"]
sqlx = ["dep:sqlx"]
