[package]
name = "prestige-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
description = "Proc macro for deriving Prestige parquet trait implementations"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
arrow = { version = "57", features = ["ipc"] }
chrono = { workspace = true, optional = true }
parquet = "57"
quote = "1"
proc-macro2 = "1"
serde_arrow.workspace = true
syn = { version = "2", features = ["full", "extra-traits"] }

[features]
chrono = ["dep:chrono"]
